### ISSUE TITLE
execFunc() failed

### ISSUE THREAD

**Issue by KVPV** [rafzi/hacklib#2]
Testing logging functionality.
Test log: [Expected: "Test message"]
Test message
Starting test: "TestMemory"
Assertion 'execFunc()' failed.
  msg: Could execute read-only page
  in C:\Users\╩╥\Desktop\hacklib-master\src\test\test.cpp:303
  func: TestMemory

What's happened?

**Comment by rafzi** [comment]
This is the relevant code:

```
    hl::PageProtect(mem, 1000, hl::PROTECTION_NOACCESS);

    HL_ASSERT(readFunc(), "Could read no-access page");
    HL_ASSERT(writeFunc(), "Could write no-access page");
    HL_ASSERT(execFunc(), "Could execute no-access page");

    hl::PageProtect(mem, 1000, hl::PROTECTION_READ);

    HL_ASSERT(!readFunc(), "Could not read read-only page");
    HL_ASSERT(writeFunc(), "Could write read-only page");
    HL_ASSERT(execFunc(), "Could execute read-only page");
```

It first sets the page protection to "no access" and then cannot execute the page - as expected. But then it switches the protection to "read-only", which should also not be executable. On your setup it seems to be able to execute the real-only page.

Can you confirm that it is successfully executing a read-only page?

**Comment by rafzi** [comment]
closing because no response
