### ISSUE TITLE
How to build and compile hacklib and hacklib-gw2 into functional gw2 ESP.dll

### ISSUE THREAD

**Issue by dasfalco** [rafzi/hacklib#6]
As the title says ,where do i start?
is there any1 willing to do it  for me or point me in the direction to figure it out myself>?

**Comment by rafzi** [comment]
Hi, this is a C++ library, intended to be used by C++ developers to build programs. This does not include any programs itself, like an ESP.

If you'd still like to go ahead with this approach, the next steps depend on your background. E.g. do you know Programming, C++, CMake?
