### ISSUE TITLE
Hello, please help. This library failed to compile with hacklib_gw2.

### ISSUE THREAD

**Issue by Jai-wei** [rafzi/hacklib#8]
Hello, I'm compiling the `hacklib_gw2` library, and following the instructions, I put it under the `hacklib/src` folder.
when I opened the vs2017 project file `hacklib_project.sln` after cmake, I got an error when compiling:
```
C2039 'RSI': not a member of 'hl::CpuContext_x86' hacklib_gw2 (hacklib_gw2\hacklib_gw2)
C2039 'RDI': not a member of 'hl::CpuContext_x86' hacklib_gw2 (hacklib_gw2\hacklib_gw2)
```
I found that the problem came from the definition of `CpuContext` under `hooker.h`:
```c++
#ifdef ARCH_64BIT
typedef CpuContext_x86_64 CpuContext;
#else
typedef CpuContext_x86 CpuContext;
#endif
```
And `CMakeLists.txt` has defined the following conditions:
```cmake
IF(CMAKE_SIZEOF_VOID_P EQUAL 8)
    SET(ARCH_64BIT TRUE)
    ADD_DEFINITIONS(-DARCH_64BIT)
    SET(PROJ_BIN        ${PROJ_ROOT}/bin64)
    SET(PROJ_LIB        ${PROJ_ROOT}/lib64)
ELSE()
    SET(PROJ_BIN        ${PROJ_ROOT}/bin)
    SET(PROJ_LIB        ${PROJ_ROOT}/lib)
ENDIF()
```
I don't know why he didn't define it as `CpuContext_x86_64`, which caused the compilation to fail.
I hope you can take the time out of your busy schedule to answer my questions, I'd be very grateful!

**Comment by Jai-wei** [comment]
Sorry, it’s a problem with my cmake. `Hacklib_gw2d.lib` and `hacklibd.lib` have been successfully compiled so far.

**Comment by rafzi** [comment]
Glad you could solve the issue. Yes, this is related to CMake being configured with a 32-bit generator. If you use a current CMake and Visual Studio, the default should be 64-bit though.

Note that you should not get a static library (.lib), but a dynamic one (.dll) for the hacklib_gw2 target, because that one will need to be injected into the target process.
